Notebook/Notebook/Controllers/NoteController.cs
using BuisnessLogic;
using Common;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.Security;

namespace Notebook.Controllers
{
    public class NoteController : Controller
    {
        private readonly IUserService userService = new UserService();

        private readonly INoteService noteService = new NoteService();

        private readonly ICategoryService categoryService = new CategoryService();

        [HttpGet]
        [Authorize]
        public ActionResult Notes()
        {
            ViewBag.Title = "Notes";

            string login = FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name;

            int? userRoleId = userService.GetUserRoleIdByLogin(login);

            if (userRoleId != null)
            {
                if (userRoleId < 3)
                {
                    ViewBag.Layout = "~/Views/Shared/AdvLayout.cshtml";

                    ViewBag.SearchType = "AdvSearch";
                }
                else
                {
                    ViewBag.Layout = "~/Views/Shared/Layout.cshtml";

                    ViewBag.SearchType = "Search";
                }

                List<NoteInfoModel> model = noteService.GetNotesInfoByUserLogin(login);

                if (model!=null)
                {
                    return View(model);
                }

                return RedirectToAction("Index", "Error");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpGet]
        [Authorize]
        public ActionResult AddNote()
        {
            ViewBag.Title = "AddNote";

            string login = FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name;

            int? userRoleId = userService.GetUserRoleIdByLogin(login);

            if (userRoleId != null)
            {
                if (userRoleId < 3)
                {
                    ViewBag.Layout = "~/Views/Shared/AdvLayout.cshtml";
                }
                else
                {
                    ViewBag.Layout = "~/Views/Shared/Layout.cshtml";
                }

                List<Category> categories = categoryService.GetCategories();

                if (categories != null)
                {
                    return View(new NoteAddModel()
                    {
                        Notes = noteService.GetNotesInfoByUserLogin(login),
                        Categories = categories,
                        User = new UserInfoModel()
                        {
                            Login = login
                        }
                    });
                }

                return RedirectToAction("Index", "Error");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpPost]
        [Authorize]
        public ActionResult AddNote(NoteAddModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (noteService.AddNote(model))
            {
                return RedirectToAction("Notes");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditNote(int? noteId)
        {
            ViewBag.Title = "EditNote";

            if (noteId != null)
            {
                string login = FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name;

                int? userRoleId = userService.GetUserRoleIdByLogin(login);

                if (userRoleId != null)
                {
                    if (userRoleId < 3)
                    {
                        ViewBag.Layout = "~/Views/Shared/AdvLayout.cshtml";
                        ViewBag.ShowUser = true;
                    }
                    else
                    {
                        ViewBag.Layout = "~/Views/Shared/Layout.cshtml";
                        ViewBag.ShowUser = false;
                    }

                    Note note = noteService.GetNoteById((int)noteId);

                    if (note != null)
                    {
                        List<Category> categories = categoryService.GetCategories();

                        if (categories != null)
                        {
                            return View(new NoteEditModel()
                            {
                                Id = note.Id,
                                Name = note.Name,
                                Date = note.Date,
                                Description = note.Description,
                                Imglink = note.Imglink,
                                CategoryId = note.Category.Id,
                                Notes = noteService.GetNotesInfoByUserLogin(login),
                                LinkedNotesIds = noteService.GetLinkedNotesIds((int)note.Id),
                                Categories = categories,
                                User = note.User
                            });
                        }

                        return RedirectToAction("Index", "Error");
                    }

                    return RedirectToAction("Index", "Error");
                }

                return RedirectToAction("Index", "Error");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpPost]
        [Authorize]
        public ActionResult EditNote(NoteEditModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (noteService.EditNote(model))
            {
                return RedirectToAction("Notes");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpGet]
        [Authorize]
        public ActionResult ShowNote(int? noteId)
        {
            ViewBag.Title = "EditNote";

            if (noteId != null)
            {
                string login = FormsAuthentication.Decrypt(Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name;

                int? userRoleId = userService.GetUserRoleIdByLogin(login);

                if (userRoleId != null)
                {
                    if (userRoleId < 3)
                    {
                        ViewBag.Layout = "~/Views/Shared/AdvLayout.cshtml";
                        ViewBag.ShowUser = true;
                    }
                    else
                    {
                        ViewBag.Layout = "~/Views/Shared/Layout.cshtml";
                        ViewBag.ShowUser = false;
                    }

                    Note model = noteService.GetNoteById((int)noteId);

                    if (model != null)
                    {
                        return View(model);
                    }

                    return RedirectToAction("Index", "Error");
                }

                return RedirectToAction("Index", "Error");
            }

            return RedirectToAction("Index", "Error");
        }

        [HttpGet]
        [Authorize]
        public ActionResult DeleteNote(int? id)
        {
            if (noteService.DeleteNote(id))
            {
                return RedirectToAction("Notes");
            }

            return RedirectToAction("Index", "Error");
        }
    }
}

Notebook/Notebook/Views/Note/AddNote.cshtml
@model Common.NoteAddModel

@{
    Layout = ViewBag.Layout;
}

<div id="note">
    @using (Html.BeginForm("AddNote", "Note", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "" })

        @Html.HiddenFor(model => model.User.Login)

        <div>
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "" })
            <div>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "" })
            </div>
        </div>

        <div>
            <lable>Category</lable>
            <select name="CategoryId">
                @foreach (var item in Model.Categories)
                {
                    <option value="@item.Id">@item.Name</option>
                    <lable>@item.Name</lable>
                }
            </select>
        </div>

        <div>
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "" })
            <div>
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "" })
            </div>
        </div>

        <input type="file" name="ImgFile" accept="image/*" />

        <div>
            <span>Add note link</span>
            <table>
                <tr>
                    <th></th>
                    <th>
                        Note name
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Category
                    </th>
                </tr>
                @if (Model.Notes != null)
                {
                    for (int i = 0; i < Model.Notes.Count; i++)
                    {
                        @Html.HiddenFor(model => model.Notes[i].Id)
                        <tr>
                            <td>@Html.CheckBoxFor(model => model.Checked[i])</td>
                            <td>@Model.Notes[i].Name</td>
                            <td>@Model.Notes[i].Date.Year-@Model.Notes[i].Date.Month-@Model.Notes[i].Date.Day</td>
                            <td>@Model.Notes[i].Category.Name</td>
                        </tr>
                    }
                }
            </table>
        </div>

        <div>
            <input type="submit" value="Add" />
        </div>
    }
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Notebook/Notebook/Views/Note/EditNote.cshtml
@model Common.NoteEditModel

@{
    Layout = ViewBag.Layout;
}

<div id="note">
    @if (ViewBag.ShowUser && Model.User.Login != FormsAuthentication.Decrypt(HttpContext.Current.Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name)
    {
        <lable>User: @Model.User.Login (@Model.User.Role.Name)</lable>
    }

    @using (Html.BeginForm("EditNote", "Note", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "" })

        @Html.HiddenFor(model => model.User.Login)

        @Html.HiddenFor(model => model.Id)

        @Html.HiddenFor(model => model.Date)

        @Html.HiddenFor(model => model.Imglink)

        <div>
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "" })
            <div>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "" })
            </div>
        </div>

        <div>
            <lable>Category</lable>
            <select name="CategoryId">
                @foreach (var item in Model.Categories)
                {
                    if (item.Id == Model.CategoryId)
                    {
                        <option value="@item.Id" selected>@item.Name</option>
                        <lable>@item.Name</lable>
                    }
                    else
                    {
                        <option value="@item.Id">@item.Name</option>
                        <lable>@item.Name</lable>
                    }
                }
            </select>
        </div>

        <div>
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "" })
            <div>
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "" })
            </div>
        </div>

        <label>Replace image</label>
        <input type="file" name="ImgFile" accept="image/*" />

        <div>
            <span>Add note link</span>
            <table>
                <tr>
                    <th></th>
                    <th>
                        Note name
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Category
                    </th>
                </tr>
                @if (Model.Notes != null)
                {
                    for (int i = 0; i < Model.Notes.Count; i++)
                    {
                        @Html.HiddenFor(model => model.Notes[i].Id)
                        <tr>
                            <td>
                                @if (Model.LinkedNotesIds != null)
                                {
                                    if (Model.LinkedNotesIds.Contains((int)Model.Notes[i].Id))
                                    {
                                        @Html.CheckBoxFor(model => model.Checked[i], new { @checked = "checked" });
                                    }
                                    else
                                    {
                                        @Html.CheckBoxFor(model => model.Checked[i]);
                                    }
                                }
                                else
                                {
                                    @Html.CheckBoxFor(model => model.Checked[i]);
                                }
                            </td>
                            <td>@Model.Notes[i].Name</td>
                            <td>@Model.Notes[i].Date.Year-@Model.Notes[i].Date.Month-@Model.Notes[i].Date.Day</td>
                            <td>@Model.Notes[i].Category.Name</td>
                        </tr>
                    }
                }
            </table>
        </div>

        <div>
            <input type="submit" value="Edit" />
        </div>
    }
</div>

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Notebook/Notebook/Views/Note/Notes.cshtml
@model List<Common.NoteInfoModel>

@{
    Layout = ViewBag.Layout;
}

<table>
    <tr>
        <th>
            Note name
        </th>
        <th>
            Date
        </th>
        <th>
            Category
        </th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    <a href="~/Note/ShowNote/?noteId=@item.Id">@item.Name</a>
                </td>
                <td>
                    <a href="~/Search/@ViewBag.SearchType/?searchType=1&requestText=@item.Date.Year-@item.Date.Month-@item.Date.Day">@item.Date.Year-@item.Date.Month-@item.Date.Day</a>
                </td>
                <td>
                    <a href="~/Search/@ViewBag.SearchType/?searchType=2&requestText=@item.Category.Name">@item.Category.Name</a>
                </td>
                <td>
                    <a href="~/Note/EditNote/?noteId=@item.Id">Edit</a>
                </td>
                <td>
                    <a href="~/Note/DeleteNote/?id=@item.Id">Delete</a>
                </td>
            </tr>
        }
    }
</table>

Notebook/Notebook/Views/Note/ShowNote.cshtml
@model Common.Note

@{
    Layout = ViewBag.Layout;
}

<div id="note">
    @if (ViewBag.ShowUser && Model.User.Login != FormsAuthentication.Decrypt(HttpContext.Current.Request.Cookies[FormsAuthentication.FormsCookieName].Value).Name)
    {
        <lable>User: @Model.User.Login (@Model.User.Role.Name)</lable>
    }

    <div>
        <label>Name: @Model.Name</label>
    </div>
    
    <div>
        <label>Date: @Model.Date.Year-@Model.Date.Month-@Model.Date.Day</label>
    </div>
    
    <div>
        <label>Category: @Model.Category.Name</label>
    </div>
    
    <div>
        <span>Linked notes:</span>
        <table>
            <tr>
                <th>
                    Note name
                </th>
                <th>
                    Date
                </th>
                <th>
                    Category
                </th>
            </tr>
            @if (Model.LinkedNotes != null)
            {
                foreach (var item in Model.LinkedNotes)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.Date.Year-@item.Date.Month-@item.Date.Day</td>
                        <td>@item.Category.Name</td>
                    </tr>
                }
            }
        </table>
    </div>
    
    <div>
        <img src="@Model.Imglink" />
    </div>
</div>